Cen 73 / Products Page
manuel-salvador/cenius pull request #13
Opened 2023-08-04 00:48 UTC by manuel-salvador

## Resumen
Desarrollada pagina de productos en el path _/products

## Cambios Realizados

- Modificado tsconfig.app.json para que acepte archivos json
- Creado products.json que es un mock de productos
- Modificado router.ts para agregar la ruta /products
- Creado archivo types/index.ts para poner las interface que se usan
- Creado componente ProductsView

# Comprobación de Calidad

- [ ] Se han añadido pruebas unitarias relevantes.
- [ ] Se han ejecutado todas las pruebas existentes.
- [ ] Otros: _(especificar)_

## Revisores Asignados

@saracast909

2023-08-04 04:57 UTC, saracast909 approved these changes

2023-08-04 14:10 UTC, brayanlaiton0116 requested changes

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +  id: -1,
por que el id esta en numero negativo

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +        <v-toolbar class="bg-white pl-5 pt-2">
seria recomendable poner los estilos con un nombre y determinarlos en style por organizacion

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +                <span class="text-h5">{{ formTitle }}</span>
seria recomendable poner los estilos con un nombre y determinarlos en style por organizacion

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +              <span class="text-h5 text-center mt-3"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> -              <v-card-title class="text-h5 text-center"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> -              <v-card-title class="text-h5 text-center"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:10 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +              <span class="text-h5 text-center mt-3"
seria recomendable poner los estilos con un nombre y determinarlos en style por organización

2023-08-04 14:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +  id: -1,
Esto es porque al tener el -1 y usarlo como indice no seleccionaria ningun elemento del array de productos por lo que funcionaria como un default, mismo en un commit mas adelante se reemplazo el ref para que inicie con la variable deafultItem

2023-08-04 14:16 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +        <v-toolbar class="bg-white pl-5 pt-2">
En este caso estoy usando las Utility Classes de vuetify, las elimino, creo una clase y pongo los mismos estilos dentro de la etiqueta style?

Dejo el link a las utility classes que están en la documentación:
https://vuetifyjs.com/en/styles/border-radius/

2023-08-04 14:17 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +                <span class="text-h5">{{ formTitle }}</span>
En este caso estoy usando las Utility Classes de Vuetify, las elimino, creo una clase y pongo los mismos estilos dentro de la etiqueta style?

Dejo el link a las utility classes que están en la documentación:
https://vuetifyjs.com/en/styles/border-radius/

2023-08-04 14:17 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
En este caso estoy usando las Utility Classes de Vuetify, las elimino, creo una clase y pongo los mismos estilos dentro de la etiqueta style?

Dejo el link a las utility classes que están en la documentación:
https://vuetifyjs.com/en/styles/border-radius/

2023-08-04 14:17 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
En este caso estoy usando las Utility Classes de Vuetify, las elimino, creo una clase y pongo los mismos estilos dentro de la etiqueta style?

Dejo el link a las utility classes que están en la documentación:
https://vuetifyjs.com/en/styles/border-radius/

2023-08-04 14:17 UTC, manuel-salvador commented on src/views/ProductsView.vue
> -              <v-card-title class="text-h5 text-center"
En este caso estoy usando las Utility Classes de Vuetify, las elimino, creo una clase y pongo los mismos estilos dentro de la etiqueta style?

Dejo el link a las utility classes que están en la documentación:
https://vuetifyjs.com/en/styles/border-radius/

2023-08-04 14:33 UTC, brayanlaiton0116 commented on src/views/ProductsView.vue
> +        <v-toolbar class="bg-white pl-5 pt-2">
pero por organizacion seria que crearas una clase y agregues los estilos

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +        <v-toolbar class="bg-white pl-5 pt-2">
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +                <span class="text-h5">{{ formTitle }}</span>
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <v-card-title class="text-h5 text-center"
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <span class="text-h5 text-center mt-3"
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> -              <v-card-title class="text-h5 text-center"
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> -              <v-card-title class="text-h5 text-center"
Corregido

2023-08-04 18:13 UTC, manuel-salvador commented on src/views/ProductsView.vue
> +              <span class="text-h5 text-center mt-3"
Corregido

2023-08-08 20:35 UTC, brayanlaiton0116 approved these changes

2023-08-08 21:32 UTC, merged