CEN-17
manuel-salvador/cenius pull request #6
Opened 2023-07-17 17:43 UTC by brayanlaiton0116

## Resumen
_[We added the planning of two components which were the header and the sidebar with desktop and responsive designs and performance of the page..]_

## Cambios Realizados
    No change
_[Proporcionar una lista de los cambios realizados en este Pull Request.]_

- _ej. Hearder is implemented._
- _ej. Sidebar is implemented._
- _ej. Dynamic menu with selectable._

# Comprobación de Calidad

_[We add the tests performed for desktop and responsive through the operation of the page in detail..]_

- [ ] Se han añadido pruebas unitarias relevantes.
- [ ] Se han ejecutado todas las pruebas existentes.
- [ ] Otros: _(especificar)_

## Revisores Asignados

_[Added to review the detail of the positioning of the components with their respective equal size and functioning of each one, as well as the revision of the design and qualification of the page. .]_

@manuel-salvador 
@Jenny-Castro

2023-07-17 18:16 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <img class="logoUno" src="src/assets/logo/cenius.png" />
Error al importar imagen en build time
![image](https://github.com/manuel-salvador/cenius/assets/85590962/76333f4c-cbda-47ce-8132-848d298554cc)

Por favor arreglar esto, una posible solucion es importarlo asi @/assets/
Se requiere modificar el codigo y ejecutar el comando build para revisar que no existan problemas

2023-07-17 19:13 UTC, manuel-salvador requested changes
Hay correcciones en los comentarios, mejorar y arreglar código en general especialmente el código CSS, usar el formateador de Prettier, si se usa guardado automático entonces ejecutar la herramienta sino guardar manualmente cada vez que se hace los cambios y esto formateara el código automáticamente.

2023-07-17 19:13 UTC, manuel-salvador commented on src/assets/base.css
Por favor dejar el archivo base.css como viene desde la rama main

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <div>
Aca se debe recibir un slot para realizar la respectiva componetizacion y que el contenido sea dinamico

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +
Revisar saltos de linea

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  .search__btn {
Clase se repite, esta es una

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  .search__btn {
Clase se repite, esta es la segunda

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +.navbar__icono{
Por favor identar bien

2023-07-17 19:13 UTC, manuel-salvador commented on src/router/index.ts
> +      // route level code-splitting
eliminar comentarios que vienen de la documentacion

2023-07-17 19:13 UTC, manuel-salvador commented on src/views/DashboardView.vue
> +import MainLayout from '../layouts/MainLayout.vue'
Ver si se puede importar con el alias @ que apunta a src (no obligatorio pero si deseable)

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +* {
Eliminar los estilos de * ya que esta implementado en el archivo base.css y no es una buena practica aplicar estilos globales.

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +<style>
Añadir el atributo scoped para que los estilos solo tengan efecto en este componente, se encontraron saltos de linea dentro de las clases aplicadas, por favor corregir el formateo del codigo.

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
Por favor en los estilos evitar usar posiciones relativas y absolutas a no ser que sea necesario como ventanas flotantes o modales, tampoco usar porcentajes para posicionamiento ya que pueden generar problemas no deseados en otras pantallas

Captura de pantalla se superponen iconos, en este caso icono de busqueda e icono de notifcaciones:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/a46e40c9-99ac-41aa-ae33-b4884868e2ff)

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  padding: -10px;
La propiedad padding no acepta valores negativos, corregir o en caso de que no sea necesario eliminar esta propiedad

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +.navigation__list {
Eliminar saltos de linea
Los valores height y width son necesarios o ya vienen con vuetify? Revisar esto

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  padding: -7px;
Padding no acepta valores negativos

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  padding:10px;
padding y margin? por favor revisar esto, si se esta usando para generar espacio entre el padre y este elemento darle padding al padre, si solo se quiere poner espacio en los costados usar gap en el padre o usar padding: valorX valorY;

Documentacion de padding:
https://developer.mozilla.org/es/docs/Web/CSS/padding

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  gap: -25px;
valor negativo no valido en la propiedad gap, si se usa un gap por favor usar row-gap o column-gap segun corresponda

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  position: relative;
evitar usar posiciones relativas para posicionamiento

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  position: absolute;
no usar absolute para creacion de layouts puede generar problemas a no ser que se requiera en ventanas flotantes o modales

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    position: absolute;
Evitar position absolute

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    height: 7%;
evitar usar porcentaje, preferible no usarlo para que tome el alto del contenido o usar px

2023-07-17 19:13 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <div class="search__btn">
Evitar usar diminutivos y modificar search__btn o search__button ya que genera confusión
- Consejo, agregaría wrapper en alguna clase _ej. pepito__wrapper_

2023-07-19 21:58 UTC, manuel-salvador requested changes
Se siguen encontrando errores y malas prácticas, por favor revisar minuciosamente

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <img class="logoUno" src="src/assets/logo/cenius.png" />
- Colocar en vez de logoUno y logoDos las clases logoUno=isotype y logoDos=logo
- Tambien importante agregar la el atributo alt en las etiquetas img

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <div class="search__btn">
Evitar usar diminutivos como btn, search__btn = search__button

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        </v-div>
- v-div no existe en Vuetify. ¿Es un componente tuyo?

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +          <v-btn class="search__icons" prepend-icon="mdi-magnify"></v-btn>
- es solo un icono deberia ser en singular, bien que este en ingles 🤝

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        <div class="navbar__icono">
es un navbar que tiene iconos, deberia ir en plural y en ingles

Corregir los hijos la clase para que siga BEM CSS, deberian quedar asi:
class="navbar__icon navbar__icon--bell" y class="navbar__icon navbar__icon--account-circle"

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>          <div class="navigation__itemUno">
Corregir clase navigation__itemUno, no esta en ingles y no hace referencia a un solo icono sino que a un grupo de iconos, podria ser asi:
class="navigation__group-items--first"

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>          <div class="navigation__itemDos">
Lo mismo que arriba pero en vez de --first tiene que ir --second

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +<style>
Por favor añadir el atributo scoped

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        </div>
- Semanticamente se recomienda que se use h2 para el nombre y h3 para el saludo

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>  }
- En vez de usar position relative, margin top y top se recomienda ponerle al padre un display: flex, flex-direction: column y justify-content: space-between

Sin las correcciones dependiendo de la pantalla el grupo de iconos de abajo no queda como deberia

![image](https://github.com/manuel-salvador/cenius/assets/85590962/3d47d866-0bea-4a4e-9446-cea86d89fa76)

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>  }
- Se requiere agregar height del mismo valor que width para que el logo se visualice correctamente

Sin height:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/8c668122-4779-4cf0-b1a8-8a4b9b8cd711)

Con height:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/c4cdf75e-664c-4771-ae18-8655f7321374)

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  left: 770%;
- No usar left, right, etc si no es necesario ya que puede generar problemas
- Se recomienda trabajar layouts con grid, flex, padding y margin

Problema que se encontro:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/12aea046-c0ae-44bc-a047-37b9a19b132e)

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  left: 770%;
- No usar left, right, etc si no es necesario ya que puede generar problemas
- Se recomienda trabajar layouts con grid, flex, padding y margin

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
⚠ Evitar usar porcentajes para los heights ⚠

IPhone SE:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/4f31eedb-6574-4374-bf97-ccbb07c3bb5b)

IPhone XR:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/9c269fce-f07a-444d-8409-55ffdbd0f47c)

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    left: 114%;
⚠ No usar porcentajes en posicionamiento para la construcción del layout

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    left: 115%;
⚠ No usar porcentajes en posicionamiento para la construcción del layout

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  .search__btn {
⚠ Error no corregido

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  .search__btn {
⚠ Error no corregido

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    top: 45%;
⚠ Evitar porcentaje para posicionamiento

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    left: 8%;
⚠ Evitar porcentaje para posicionamiento

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>      top: 2%;
⚠ Evitar porcentaje para posicionamiento

2023-07-19 21:58 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +    right: 30%;
⚠ Evitar porcentaje para posicionamiento

2023-07-28 13:42 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +
Correggido

2023-07-28 13:42 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +  .search__btn {
corregido

2023-07-28 13:42 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +  .search__btn {
corregido

2023-07-28 14:05 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>        </v-div>
corregido

2023-07-28 14:06 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +          <v-btn class="search__icons" prepend-icon="mdi-magnify"></v-btn>
corregido

2023-07-28 14:06 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +    top: 45%;
Corregido

2023-07-28 14:07 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +    left: 8%;
Corregido

2023-07-28 14:07 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>      top: 2%;
Corregido

2023-07-28 14:28 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +        <img class="logoUno" src="src/assets/logo/cenius.png" />
Corregido

2023-07-28 14:29 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +        <div>
No creo que sea necesario en esta función

2023-07-28 14:30 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +
Corregido

2023-07-28 14:30 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +  position: relative;
Corregido

2023-07-28 14:30 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +  position: absolute;
Corregido

2023-07-28 14:30 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +    position: absolute;
Corregido

2023-07-28 14:38 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +          <v-btn class="search__icons" prepend-icon="mdi-magnify"></v-btn>
corregido

2023-07-28 14:38 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>        <div class="navbar__icono">
corregido

2023-07-28 14:38 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +    left: 8%;
corregido

2023-07-28 14:39 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>      top: 2%;
corregido

2023-07-28 14:39 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +    right: 30%;
corregido

2023-07-28 15:03 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <div>
El componente MainLayout se va a usar en diferentes paginas y tiene que aceptar contenido principal por lo que es dinamico, tambien esta aclarado en la tarea asignada en Jira [CEN-17](https://globant-saracastillo.atlassian.net/browse/CEN-17)

2023-07-28 16:24 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
> +        <div>
Acabo de corregir esto.

2023-07-28 17:27 UTC, manuel-salvador requested changes, later dismissed

2023-07-28 17:27 UTC, manuel-salvador commented on src/views/DashboardView.vue
> +import MainLayout from '../layouts/MainLayout.vue'
Se intento? No se pudo hacer?

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        </div>
Se olvido esta correccion o no esta de acuerdo?

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        <div class="navbar__icono">
sigue igual, consejo, usar esta clase "navbar__icons"

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>        <div class="navbar__icono">
La clase de los iconos hijos no se corrigieron, siguen igual:
![image](https://github.com/manuel-salvador/cenius/assets/85590962/2a78d3a3-245b-43db-b4da-d1b1204e482f)

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>          <div class="navigation__itemUno">
⚠ Por favor corregir

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>          <div class="navigation__itemDos">
⚠ Por favor corregir

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <div>
Sigue apareciendo un div con un h1 y el texto Hello, vi el slot pero no esta bien implementado, te dejo un ejemplo de como lo implemente en el Layout temporal [Ejemplo CEN-59 Temp Layout](https://github.com/manuel-salvador/cenius/blob/9962fe60e6b22bbe549b471b68544c053f78f3c3/src/components/TempLayout.vue#L33)

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +.navigation__list {
Por favor responder este comentario

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
>  }
⚠ No usar position relative, usar cosas nativas de vuetify o buscar ejemplos, buscando encontre que se usa esto para hacer lo requerido, lo probe y funciono correctamente, por favor adaptarlo para que funcione con el layout que se esta haciendo

``` html
...
<v-navigation-drawer>
    <v-list>
        <!-- aca van los items de las rutas -->
    </v-list>
    <template v-slot:append>
        <div>
            <button>Ejemplo</button>
        </div>
    </template>
</v-navigation-drawer>
```

Link del recurso: [Navigation drawer Misc](https://vuetifyjs.com/en/components/navigation-drawers/#misc)

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +  position: absolute;
Sigue con absolute, ya que es container sugiero que se use relative para que el search button siga funcionando correctamente con el position absolute

Recomiendo la lectura de este articulo: [Cómo usar la propiedad de posición en CSS para alinear elementos
](https://www.freecodecamp.org/espanol/news/como-usar-la-propiedad-posicion-en-css-para-alinear-elementos)

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +
Eliminar este salto de linea

2023-07-28 17:27 UTC, manuel-salvador commented on src/layouts/MainLayout.vue
> +        <img class="IsoType" :src="Logo" />
Bien el cambio, aunque recomiendo cambiar todo a lowercase quedando asi: isotype

2023-08-10 20:19 UTC, saracast909 requested changes

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>    .navigation__itemDos {
La clase debe estar en ingles

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>    .navbar__iconoUno {
La clase debe estar en ingles

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>  .navbar__iconoDos:hover {
Clase en ingles

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>  .navbar__icono {
cambia "Icono" a "Icon"

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>  .navigation__itemDos {
cambia "ItemDos" a "ItemTwo"

2023-08-10 20:19 UTC, saracast909 commented on src/layouts/MainLayout.vue
>  .navigation__itemUno {
Cambia "itemUno" a "itemOne"

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>    .navigation__itemDos {
okey, me pongo a trabajar en eso :)

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>    .navbar__iconoUno {
okey, me pongo a trabajar en eso :)

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>  .navbar__iconoDos:hover {
okey, me pongo a trabajar en eso :)

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>  .navbar__icono {
okey, me pongo a trabajar en eso :)

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>  .navigation__itemDos {
okey, me pongo a trabajar en eso :)

2023-08-10 20:22 UTC, brayanlaiton0116 commented on src/layouts/MainLayout.vue
>  .navigation__itemUno {
okey, me pongo a trabajar en eso :)

2023-08-21 23:45 UTC, saracast909 approved these changes

2023-08-21 23:45 UTC, saracast909 commented on src/components/MainLayout.vue
> +      <div class="navbar__icon">
navbar__icons

2023-08-22 02:27 UTC, brayanlaiton0116 commented on src/components/MainLayout.vue
> +      <div class="navbar__icon">
Quedaría igual que la otra clase sara ?

2023-08-22 02:28 UTC, brayanlaiton0116 commented on src/components/MainLayout.vue
> +      <div class="navbar__icon">
y puedes mirar los comentaris de manu y el me dijo que lo dejara navbar__icon

2023-08-22 02:40 UTC, brayanlaiton0116 commented on src/components/MainLayout.vue
> +      <div class="navbar__icon">
pero dale yo lo cambio :) 

ya lo cambie.

2023-08-22 16:38 UTC, merged