CEN-59
manuel-salvador/cenius pull request #7
Opened 2023-07-25 16:23 UTC by manuel-salvador

## Resumen
Se creo un TempLayout (Layout temporal) y se uso eso para desarrollar el Dashboard, dentro de este se usan diferentes componentes creados como los charts y el mock de lastOrders para poder utilizar estos datos en la tabla del final de la pagina.
Además en el componente AreaChart.vue se usa una funcion para crear los  datos aleatoriamente y que se tengan datos ficticios de ventas de 1 año entero

## Cambios Realizados

- Modificado el router para crear ruta /dashboard
- Modificado DashboardView
- Modificado App.vue para que no aparezca el header default junto con RouterView
- Modificado App.vue para crear variables de colores que se usan repetidamente
- Creado componente TempLayout
- Instalado paquete apexcharts
- Instalado paquete vue3-apexcharts
- Modificado main.ts para que se pueda usar <apexchart> en cualquier lugar
- Creado componente AreaChart
- Creado componente DonutChart
- Creado carpeta /utils
- Creado funcion generateData en /utils
- Creado carpeta /mocks
- Creado mock lastOrdersMock en /mocks
- Modificado script dev para que abra una nueva pestaña al iniciar el servidor de desarrollo

# Comprobación de Calidad

- [ ] Se han añadido pruebas unitarias relevantes.
- [ ] Se han ejecutado todas las pruebas existentes.
- [ ] Otros: _(especificar)_

## Revisores Asignados

@brayanlaiton0116 
@saracast909

2023-07-26 13:55 UTC, saracast909 commented on src/components/AreaChart.vue
> +  let startOfYear // Movemos la declaración fuera del bloque 'case'
Escribir comentario en ingles

2023-07-26 13:55 UTC, saracast909 commented on src/components/AreaChart.vue
> +      startOfYear = new Date(today).getFullYear() // Asignamos el valor aquí
Comentario en ingles

2023-07-26 16:16 UTC, saracast909 approved these changes

2023-07-27 20:11 UTC, brayanlaiton0116 requested changes
Revisa las abreviaturas o contracciones.

2023-07-27 20:11 UTC, brayanlaiton0116 commented on src/components/AreaChart.vue
> +  let startOfYear // Movemos la declaración fuera del bloque 'case'
Comentarios en ingles

2023-07-27 20:11 UTC, brayanlaiton0116 commented on src/components/AreaChart.vue
> +    case 'ytd':
No usar abreviaturas o contracciones en el código de case 'ytd':

2023-07-27 20:11 UTC, brayanlaiton0116 commented on src/components/AreaChart.vue
> +      <button id="ytd" @click="updateData('ytd')" :class="{ active: selection === 'ytd' }">
no escribir abreviaturas o contracciones.

2023-07-27 20:13 UTC, brayanlaiton0116 approved these changes, later dismissed
se prueba correctamente

2023-07-27 21:19 UTC, manuel-salvador commented on src/components/AreaChart.vue
> +  let startOfYear // Movemos la declaración fuera del bloque 'case'
Esto ya fue corregido

2023-07-27 21:28 UTC, manuel-salvador commented on src/components/AreaChart.vue
> +  let startOfYear // Movemos la declaración fuera del bloque 'case'
Solucionado

2023-07-27 21:28 UTC, manuel-salvador commented on src/components/AreaChart.vue
> +      startOfYear = new Date(today).getFullYear() // Asignamos el valor aquí
Solucionado

2023-07-27 22:08 UTC, manuel-salvador commented on src/components/AreaChart.vue
> +    case 'ytd':
Corregido

2023-07-27 22:09 UTC, manuel-salvador commented on src/components/AreaChart.vue
> +      <button id="ytd" @click="updateData('ytd')" :class="{ active: selection === 'ytd' }">
Corregido

2023-07-27 22:13 UTC, brayanlaiton0116 approved these changes
Cambios aprobados

2023-07-27 22:15 UTC, merged